### ISSUE TITLE
Incluir Códigos dos Concelhos e Distritos na resposta

### ISSUE THREAD

**Issue by cpferreiraISQ** [jfoclpf/geoapi.pt#102]
Em complemento à informação por extenso devolvida pela API do Distrito e Concelho a que pertence um código postal. Sería importante para uma indexação mais simples de sistemas a devolução complementar dos códigos oficiais dos mesmos. 
Exemplo do Código Postal 2520-193:
- concelho: 14
- distrito: 10

Grato pela atenção

**Comment by jfoclpf** [comment]
bem visto, acrescentar ao pedido
(exemplo: https://geoapi.pt/cp/2520-193?json=belo)

os campos `codigoine_distrito` e `codigoine_municipio` podem ser adicionados facilmente

**Comment by cpferreiraISQ** [comment]
@jfoclpf algum horizonte temporal para a inclusão deste enhancement? Grato pela atenção

**Comment by jfoclpf** [comment]
@cpferreiraISQ feito

podes ver aqui dois exemplos

https://geoapi.pt/codigo_postal/1950-449?json=belo
https://geoapi.pt/codigo_postal/1950?json=belo

foram adicionados dois novos campos `codigoineDistrito` e `codigoineMunicipio` à resposta

se fizeres dinheiro com esta API, considera sff um donativo

**Comment by cpferreiraISQ** [comment]
@jfoclpf 
É para uso interno na empresa, e sim, estou a ver com o dep financeiro como poderemos proceder a um donativo bem merecido! Mais uma vez, muito grato pelo apoio (estes códigos irão nos dar muita utilidade)!

**Comment by jfoclpf** [comment]
muito agradecidos pelo eventual donativo 

resto de bom dia
