### ISSUE TITLE
Código postal 3800-042 sem informação?

### ISSUE THREAD

**Issue by cpferreiraISQ** [jfoclpf/geoapi.pt#103]
Verificou-se que o código postal 3800-042 que é válido e georreferenciado no google maps, não pertence à vossa BD.

**Comment by jfoclpf** [comment]
Olá @cpferreiraISQ 

interessante, que fontes tem para afirmar que esse CP é válido?

O [ficheiro dos CTT](https://www.ctt.pt/feapl_2/app/restricted/postalCodeSearch/postalCodeDownloadFiles.jspx) (a fonte oficial; precisa apenas de criar conta mas fazer o download é grátis) não tem esse código postal

```
$ grep ';3800;04' todos_cp.txt --text 
01;05;6684;Aveiro;109580100;Beco;do;;;Restuido;Taboeira;;;;3800;048;AVEIRO
01;05;6684;Aveiro;1520501;Rua;;Doutor;;Louren�o Peixinho;Taboeira;;;;3800;043;AVEIRO
01;05;6684;Aveiro;2090501;Rua;da;;;Lagoinha;Taboeira;;;;3800;044;AVEIRO
01;05;6684;Aveiro;2130501;Rua;da;;;Liberdade;Taboeira;;;;3800;045;AVEIRO
01;05;6684;Aveiro;226650000;Rotunda;da;;;Taboeira;Taboeira;;;;3800;043;AVEIRO
01;05;6684;Aveiro;2908100;Travessa;;;;Jo�o Maria Marques Ribeiro;Taboeira;;;;3800;048;AVEIRO
01;05;6684;Aveiro;29852100;Estrada;de;;;Taboeira;Taboeira;;;;3800;043;AVEIRO
01;05;6684;Aveiro;5090501;Rua;;;;Ant�nio Marques da Gra�a;Taboeira;;;;3800;047;AVEIRO
01;05;6684;Aveiro;5100501;Rua;de;;;Ant�nio Ribeiro da Silva;Taboeira;;;;3800;048;AVEIRO
01;05;6684;Aveiro;6180501;Travessa;de;Santo;;Ant�nio;Pa�o;;;;3800;040;AVEIRO
01;05;6684;Aveiro;6220501;Rua;de;S�o;;Jo�o;Pa�o;;;;3800;041;AVEIRO
01;05;6684;Aveiro;752310000;Beco;do;;;Mateus;Taboeira;;;;3800;048;AVEIRO
01;05;6684;Aveiro;77670501;Rua;do;;;Monte Novo;Taboeira;;;;3800;043;AVEIRO
01;05;6684;Aveiro;77680501;Rua;;;;Ant�nio Rodrigues Oliveira;;;;;3800;043;AVEIRO
01;05;6684;Aveiro;77760501;Beco;de;S�o;;Pedro;;;;;3800;043;AVEIRO
01;05;6684;Aveiro;78680501;Rua;dos;;;Agros;;;;;3800;046;AVEIRO

```

**Comment by jfoclpf** [comment]
reparei em qq caso que esse código postal aparece noutras fontes, por isso contactei os CTT para mais esclarecimentos

**Comment by jfoclpf** [comment]
Olá @cpferreiraISQ 

aparentemente esse código postal é inválido, podes confirmar [aqui](https://www.ctt.pt/feapl_2/app/open/postalCodeSearch/postalCodeSearch.jspx#fndtn-addressSearchPanel) no site dos CTT, não existe

**Comment by jfoclpf** [comment]
Maid directamente dos CTT

> Bom dia João Pimentel Ferreira,
> 
> Após análise interna, informo que efetivamente o Código Postal 3800-042 foi desativado em Abril de 2021.
> 
> De salientar ainda que, este esteve associado à toponímia não oficial na freguesia de Esgueira, sendo que por informação da autarquia esta designação foi desativada.
> 
> Agradecemos o seu contato, alguma questão adicional que surja, não hesite em contactar.
> 
> Sempre disponível. Conte connosco
> 
> Valter S.
> Apoio e Voz do Cliente
> 
> Descarregue a APP CTT e usufrua dos serviços CTT onde quer que esteja: https://www.ctt.pt/particulares/app-ctt

**Comment by cpferreiraISQ** [comment]
Muito obrigado @jfoclpf pela sua dedicação ao tema. Isso comprova que a sua API é das mais atualizadas e confiáveis à data de hoje! Grato pelo mesmo.

**Comment by jfoclpf** [comment]
muito obrigado 

sim, usamos apenas o último ficheiro oficial providenciado pelos CTT.
