### ISSUE TITLE
The API hosted in https://json.geoapi.pt is down

### ISSUE THREAD

**Issue by michellarcari** [jfoclpf/geoapi.pt#108]
Hi João,

I couldn't find another way to get in touch with you, so I thought I'd write a bug in this repo (even though the issue has nothing to do with the code, but with the server where you host it).

Are you still maintaining https://json.geoapi.pt/ API? I have a project using it and depending on what you say I might have to find a different source of information.

Obrigado!
Michell

**Comment by jfoclpf** [comment]
Hi there @michellarcari 
Yes, I am still maintaining the project at  https://json.geoapi.pt/ 
regards

**Comment by jfoclpf** [comment]
yes, yes, ASAP, there's an issue with the server

**Comment by jfoclpf** [comment]
it's already up

**Comment by michellarcari** [comment]
Thank you! It's up and running on my end.

**Comment by jfoclpf** [comment]
Great to hear, if you make money with this consider a small donation please
Thanks

**Comment by michellarcari** [comment]
I actually just developed a basic web-based CRM for free as a form to support some friends who are starting some business in Portugal, however, as a developer, I also think you deserve a donation for the great job you do. I will encourage them to support you via your link https://pt.liberapay.com/joaopimentel1980/donate

**Comment by jfoclpf** [comment]
Thank you very much :)
