### ISSUE TITLE
Ilhas

### ISSUE THREAD

**Issue by carlosefonseca** [jfoclpf/geoapi.pt#31]
Viva,

Reparei que coordenadas nas ilhas devolvem formatos diferentes…

Por exemplo, na Ilha da Madeira, aparece

```json
{
  "freguesia": "Câmara de Lobos",
  "concelho": "Câmara de Lobos",
  "ilha": "Ilha da Madeira (Madeira)"
}
```

Nos Açores aparece:

```json
{
  "freguesia": "Lajes do Pico",
  "concelho": "Lajes do Pico",
  "ilha": "Ilha do Pico"
}
```

Mantendo o formato, provavelmente deveria aparecer `Ilha do Pico (Açores)`, não?

**Comment by jfoclpf** [comment]
Boas @carlosefonseca 
demorei mais tempo porque o problema não era resolvido de forma rápida, visto que isto é um problema que deriva da fonte original, do ficheiro da direção geral do território. Em qualquer caso para o utilizador da API, não deixa de ser um problema e por isso já resolvi com ee1b2305f698f54debdff86357d7a18dc235087b

Podes verificar aqui:
 - https://geoapi.pt/gps/32.661089,-16.986038
 - https://geoapi.pt/gps/38.42797,-28.17402

Agradecido por teres detectado o problema
