### ISSUE TITLE
Obter as localidades em função das freguesias

### ISSUE THREAD

**Issue by gbast0s** [jfoclpf/geoapi.pt#33]
Viva, 

Após ter analisado a API não encontrei forma de o fazer, mas acho que seria interessante por exemplo nas localidadidas arranjar forma de obter as mesmas referenciando a freguesia.

Por exemplo com este pedido:

https://geoapi.pt/freguesia/Cuba?json=1

Obtemos diversos dados, e seria interessante tendo em conta o código postal, ou até mesmo o codigoine referenciar as localidades, visto que as mesmas já têm a "Designação Postal", no entanto para algumas freguesias não é possivel pesquisar através deste campo pois trata-se de uniões.

Não daria para fazer com que neste pedido https://geoapi.pt/cp/2495 as localidades estivessem associadas diretamente à freguesia con um código ou algo.

**Comment by jfoclpf** [comment]
Olá @gbast0s 

é isto que pretendes?

https://geoapi.pt/freguesia?codigopostal=7940-159&json=1

https://geoapi.pt/freguesia?codigoine=20701&json=1

**Comment by jfoclpf** [comment]
Ou isto, acho que é isto que queres:

https://geoapi.pt/freguesia?localidade=Cuba&json=1

podes filtrar por município

https://geoapi.pt/freguesia?localidade=Cuba&municipio=Cuba&json=1

https://geoapi.pt/freguesia?nomecompleto=Cuba&municipio=Cuba&json=1

**Comment by jfoclpf** [comment]
Tens que usar o campo `nome`

https://geoapi.pt/freguesia?nome=Cuba&json=1

**Comment by gbast0s** [comment]
O que queria era as localidades daquela freguesia, mas isso penso que não exista ainda associado.

Ou seja quando estamos a consultar os codigos postais é possivel ver a localidade desse mesmo codigo, e a designação postal.

Ora se temos a designação postal, poderiamos ter algo que a associa-se diretamente à freguesia, tinha dado como exemplo o codigoine.

**Comment by jfoclpf** [comment]
O problema é que eu acho que a designação postal nem sempre corresponde à freguesia. São bases de dados diferentes, uma é dos CTT a outra da direção geral de território, temo que não haja forma fácil de fazer a ligação

**Comment by jfoclpf** [comment]
O problema é que eu acho que a designação postal nem sempre corresponde à freguesia. São bases de dados diferentes, uma é dos CTT a outra da direção geral de território, temo que não haja forma fácil de fazer a ligação

**Comment by jfoclpf** [comment]
Exemplo, esta freguesia é Marvila mas a designação postal é Lisboa

https://geoapi.pt/cp/1950-448

**Comment by gbast0s** [comment]
Sendo assim acho que nada há a fazer.

Obrigado pelo tempo dispendido.

**Comment by jfoclpf** [comment]
Apenas seria possível enumerar as localidades postais por concelho, mas julgo que seria uma lista enorme sem interesse particular

**Comment by gbast0s** [comment]
Sim por concelho deixa de ter interesse no meu caso, mas obrigado pelo feedback.
