### ISSUE TITLE
Zonas costeiras

### ISSUE THREAD

**Issue by pedrospinto** [jfoclpf/geoapi.pt#34]
Por vezes, não é possível determinar distrito/concelho/freguesia porque a coordenada está sobre o mar, mas apenas a alguns metros da linha costeira.
Não seria possível implementar uma opção que, quando a coordenada cai fora por uma pequena margem (algumas dezenas de metros, por exemplo) devolvesse a freguesia mais próxima?

Obrigado

**Comment by jfoclpf** [comment]
Isto não é fácil, pois a biblioteca usada (polygon-lookup) para achar os polígonos não permite achar o polígono mais próximo, quando o ponto não cai dentro de nenhum polígono. Entretanto já abri um issue na página da biblioteca para perguntar se é possível.

Também estive a procurar e não parece haver nada pronto a usar para achar a distância entre um ponto e um polígono, o melhor que encontrei foi isto, mas teria ainda que testar
https://github.com/Turfjs/turf/issues/1743#issuecomment-736805738

mas sim, o issue fica aberto, vou tentar investigar melhor

**Comment by jfoclpf** [comment]
A questão está a ser analizada, mas terei que arranjar tempo para pensar melhor:
https://github.com/pelias/polygon-lookup/issues/53

**Comment by jfoclpf** [comment]
@pedrospinto estava aqui a pensar, 

uma forma bem mais fácil e simples, seria caso o GPS não detecte qualquer freguesia no ponto `(lat, lon)`, testar quatro pontos num raio de `x` metros, os quatro pontos seriam `(lat+x, lon), (lat, lon+x), (lat-x, lon), (lat, lon-x)`.

Como falamos do caso português (oceano a ocidente e a sul), a ordem de verificação, por questões de eficiência, seria:

 1. `(lat+x, lon)`
 2. `(lat, lon+x),`
 3. `(lat-x, lon)`
 4. `(lat, lon-x)`

Se bem que os pedidos deverão ser feitos em paralelo (async).

Que te parece? Quando mencionas "algumas dezenas de metros" perto da costa, falamos de quantos metros? Podes dar-me um exemplo concreto sff?

**Comment by jfoclpf** [comment]
@pedrospinto Quando mencionas "algumas dezenas de metros" perto da costa, falamos de quantos metros? Podes dar-me um exemplo concreto sff?

**Comment by jfoclpf** [comment]
Feito, exemplos:

https://geoapi.pt/gps/40.2979701469945,-8.857818236363475
https://geoapi.pt/gps/37.08536698621345,-8.254953052948299

dei uma margem de 100 metros
