### ISSUE TITLE
Bug num código postal CP3

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/geoapi.pt#36]
@waldyrious

Esta ligação dá erro
https://geoapi.pt/cp/4900-339
mas esta não dá, logo vem do frontend
https://geoapi.pt/cp/4900-339?json=1

![image](https://user-images.githubusercontent.com/3984909/188308604-64ca19ba-c9dc-475a-9fd2-a90d98bfa7d1.png)

Não há informação do polígono
https://geoapi.pt/cp/4900-339?json=1

a biblioteca turf não conseguiu desenhar polígono, ou seja, no front end desenha-se polígono apenas quando está disponível

**Comment by jfoclpf** [comment]
resolvido, verifica @waldyrious
https://geoapi.pt/cp/4900-339

**Comment by waldyrious** [comment]
Ah, tou a ver, é por só haver dois pontos e formam uma linha, não uma área. Obrigado pela resolução rápida!

**Comment by waldyrious** [comment]
Vendo melhor, são 6 pontos, mas 5 deles têm exatamente a mesma posição, e isso faz o efeito de parecer que são 2 pontos.

Será que essa sobreposição é um bug? No [output em JSON](https://geoapi.pt/cp/4900-339?json=1) eles de facto têm `id`s diferentes, mas os outros campos (`rua`, `casa` e `coordenadas`) são idênticos, o que me parece suspeito...
