### ISSUE TITLE
Reduzir tamanho dos pontos na visualização de CP3

### ISSUE THREAD

**Issue by waldyrious** [jfoclpf/geoapi.pt#38]
Quando abro um resultado de CP4, como por exemplo https://geoapi.pt/cp/4700, os pontos individuais parecem ter apenas alguns pixels de diâmetro:

![image](https://user-images.githubusercontent.com/478237/188322415-cece1b96-cb2a-4caf-a820-d2e0fb73f9a1.png)

...e não ficam mais pequenos se eu faço zoom out, ou seja, o renderer tem um tamanho mínimo para os pontos:

![image](https://user-images.githubusercontent.com/478237/188322599-1e24f629-162c-4c25-a161-046413b9ee24.png)

Mas se faço zoom in, nota-se que eles são relativamente grandes à escala dos edifícios:

![image](https://user-images.githubusercontent.com/478237/188322406-0fff1ebc-ac43-45da-aff2-6abda20d1c83.png)

O efeito é mais marcante quando a visualização é de um CP3, que por natureza começa logo num zoom mais aproximado. Por exemplo, https://geoapi.pt/cp/4700-312:

![image](https://user-images.githubusercontent.com/478237/188322667-7e9d936c-57c1-4051-971d-580445f8ab6f.png)

Era preferível que os pontos aparecessem sempre como pontos, e não como círculos. Ou seja, o diâmetro desses círculos devia ser pequeno o suficiente para ser representado como pontos em qualquer nível de zoom. Ou se calhar existe mesmo uma primitiva gráfica de pontos em vez de círculos, o que talvez até possa tornar o mapa mais ágil quando há muitos pontos a visualizar.

**Comment by jfoclpf** [comment]
Olá @waldyrious 

Obrigado pela sugestão, o tamanho dos círculos vem daqui

https://github.com/jfoclpf/geoapi.pt/blob/main/views/js/postal-code.js#L47

Qual raio para o círculo é que sugere? Neste momento está com 10.

Posso diminuir para 3 em caso de CP3.

O Leaflet não permite desenhar pontos, considera que pontos são círculos pequenos.

**Comment by waldyrious** [comment]
> Qual raio para o círculo é que sugere?

Trata-me por tu, por favor! :joy:

> O Leaflet não permite desenhar pontos, considera que pontos são círculos pequenos.

Tendo em conta que os círculos são desenhados pelo Leaflet sempre com um tamanho mínimo (isto é, nunca desaparecem por ficar demasiado pequenos), não vejo porque não se poderia meter um raio arbitrariamente pequeno (digamos, `radius: 1` ou até `radius: 0.1`) e assim apareceriam sempre com o mesmo tamanho em qualquer nível de zoom e acabariam por ser, efetivamente, pontos.

**Comment by jfoclpf** [comment]
resolvido com e5f88ca35039e21abbb1e8aae4d804eb22158bbf

obrigado @waldyrious 

![image](https://user-images.githubusercontent.com/3984909/188961619-5d3a65b5-45e7-46aa-b4e4-142f6bcdf941.png)
