### ISSUE TITLE
RESTful API

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/geoapi.pt#42]
Mudar os caminhos para

```
/municipios

/municipios/{municipio}

/municipios/{municipio}/freguesias

/freguesias/{freguesia}
```

https://restfulapi.net/resource-naming/

**Comment by waldyrious** [comment]
Em relação a isto (e tendo em conta que já mencionaram HATEOAS na [thread do reddit](https://www.reddit.com/r/devpt/comments/xvgqdb/algu%C3%A9m_quer_sugerir_mais_caminhos_para_o_geo_api/)), tenho 3 sugestões:

1) Continuar a ter o default representation como HTML, para facilitar a descoberta/experimentação/partilha, como bem argumentaste na thread do reddit
2) Implementar links entre recursos através da sintaxe do [HAL](https://en.wikipedia.org/wiki/Hypertext_Application_Language) (basicamente, com os links dentro de um elemento `_links` no JSON das respostas).
3) Implementar a mesma funcionalidade de links no output em HTML. Normalmente as APIs precisam de algo adicional como o [htmx](https://htmx.org/docs/) para suportar verbos HTTP além do GET, mas neste caso basta o plain old `<a href="...">`! :smiley:

Recomendo também esta excelente leitura, [Haters gonna HATEOAS](https://web.archive.org/web/20201111235328/timelessrepo.com/haters-gonna-hateoas), que explica muito bem o conceito, e tem passagens como esta:

> HATEOAS [...] is incredibly simple, but nobody actually does it.
> [...]
> There should be a single endpoint for the resource, and all of the other actions you’d need to undertake should be able to be discovered by inspecting that resource.
> [...]
>
> Now, when I said ‘nobody’ does this, what I meant was ‘for APIs.’ This is exactly how the Web works. Think about it. You start off on the homepage. That’s the only URL you have to know. From there, a bunch of links point you towards each state that you can reach from there. People would consider it ludicrous if they had to remember a dozen URLs to navigate a website, so why do we expect the consumers of our APIs to do so as well?

**Comment by jfoclpf** [comment]
Boas @waldyrious 

1. concordo, neste momento o tipo de resposta JSON/HTML é definido pelo campo Accept do pedido GET, acho que está bem assim

2. eu estou a tentar implementar isso, o que não compreendi ainda é como é que isso se implementa, se há alguma norma específica. Por exemplo nesta resposta para `/municipios/porto/freguesias`:

```json
{
   "nome":"Porto",
   "freguesias":[
      "Bonfim",
      "Campanhã",
      "Paranhos",
      "Ramalde",
      "União das freguesias de Aldoar, Foz do Douro e Nevogilde",
      "União das freguesias de Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória",
      "União das freguesias de Lordelo do Ouro e Massarelos"
   ]
}
```

como é que coloco os links? Na norma [HATEOAS](https://restfulapi.net/hateoas/) (usada para o RESTful, que queremos seguir), eles usam este exemplo (vê também o exemplo da [página](https://en.wikipedia.org/wiki/HATEOAS) da Wikipédia)

```json
{
    "departmentId": 10,
    "departmentName": "Administration",
    "locationId": 1700,
    "managerId": 200,
    "links": [
        {
            "href": "10/employees",
            "rel": "employees",
            "type" : "GET"
        }
    ]
}
```

Que te parece então?

```json
{
   "nome":"Porto",
   "freguesias":[
      "Bonfim",
      "Campanhã",
      "Paranhos",
      "Ramalde",
      "União das freguesias de Aldoar, Foz do Douro e Nevogilde",
      "União das freguesias de Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória",
      "União das freguesias de Lordelo do Ouro e Massarelos"
   ],
   "links": [
     {
       "freguesia": "Bonfim",
       "href": "/freguesias/bonfim",
       "rel": "freguesia",
       "type": "GET"
     },
     {
       "freguesia": "Campanhã",
       "href": "/freguesias/campanhã",
       "rel": "freguesia",
       "type": "GET"
     }
   ]
}
```

3. Já está, olha por exemplo: https://geoapi.pt/municipios/porto/freguesias

**Comment by jfoclpf** [comment]
> Recomendo também esta excelente leitura, [Haters gonna HATEOAS](https://web.archive.org/web/20201111235328/timelessrepo.com/haters-gonna-hateoas), que explica muito bem o conceito, e tem passagens como esta:

não percebi o teu ponto, estás contra usarmos HATEOS, em prol de HAL, é isso?

**Comment by waldyrious** [comment]
> como é que coloco os links? Na norma [HATEOAS](https://restfulapi.net/hateoas/) (usada para o RESTful, que queremos seguir), eles usam este exemplo (vê também o exemplo da [página](https://en.wikipedia.org/wiki/HATEOAS) da Wikipédia)

Nota que o HATEOAS é uma descrição high-level, não indica uma sintaxe específica a ser seguida. A página que linkas dá um exemplo, mas não é prescritivo (aliás, eles mesmo dizem: "JSON does not have any universally accepted format for representing links between two resources").

No entanto, eles mencionam mais abaixo, na secção "HATEOAS References", que há dois formatos que são frequentemente usados para implementar HATEOAS com APIs em JSON: [RFC 5988 (web linking)](https://tools.ietf.org/html/rfc5988) e [Hypermedia API Language (HAL)](https://en.wikipedia.org/wiki/Hypertext_Application_Language), que foi o que mencionei acima.

Eu não tenho grande conhecimento desta área, mas pelo pouco que li, parece-me que o HAL é mais prático porque define especificamente uma sintaxe JSON, enquanto que o RFC 5988 é mais genérico para links na web, e não tem qualquer referência a JSON em particular.

Eu nunca implementei o HAL pessoalmente, por isso não te posso dizer exatamente o que recomendam em relação a esta estrutura, mas parece-me que entre os exemplos da Wikipédia e a especificação informal em https://stateless.group/hal_specification.html (e a spec formal em https://datatracker.ietf.org/doc/html/draft-kelly-json-hal-08), haverá informação suficiente para se conseguir seguir o modelo.

<sub>(Se estiveres familiarizado com [JSON Schema](https://json-schema.org/), até podes usar um validador como o https://jsonschema.dev, usando como base o spec contribuído [aqui](https://github.com/scottsmith130/hal-json-schema/blob/master/hal.json) — embora a [versão mais recente](https://github.com/evently-cloud/hal-json-schema/blob/main/hal.json) do PR https://github.com/scottsmith130/hal-json-schema/pull/1 possa ser mais apropriada).</sub>

Mas honestamente, acho que o modelo que segues no exemplo que deste acima, desde que aplicado de forma consistente, seria suficiente para a API respeitar os princípios do HATEOAS. Talvez considera também meter (nesse exemplo que deste) um link com `"rel": "distrito"`, para se poder navegar não apenas para baixo mas também para cima :)

> Já está, olha por exemplo: [geoapi.pt/municipios/porto/freguesias](https://geoapi.pt/municipios/porto/freguesias)

Ah sim, excelente! Falha minha não ter ido verificar heheh.

> não percebi o teu ponto, estás contra usarmos HATEOS, em prol de HAL, é isso?

Hahah, não, de todo, pelo contrário! De facto o título desse artigo é algo provocador, mas acho que é só a brincar com o acrónimo ter "hate" nele (quando podia muito bem ter sido chamado de "HEAS" por exemplo).

**Comment by jfoclpf** [comment]
Muito obrigado @waldyrious 
que te parece esta resposta, sugerias alguma solução destas?
https://stackoverflow.com/a/73959498/1243247

**Comment by waldyrious** [comment]
Confesso que o discurso nessa thread so StackOverflow já está além do meu conhecimento :) eles levantam bons pontos, mas não consegui seguir tudo o que disseram. Prefiro evitar comentar nesse caso, porque o meu conhecimento deste tópico é ainda superficial.

**Comment by waldyrious** [comment]
Hm, acho o campo `_embedded` não teria apenas a key `_links`, certo? Presumo que estejas a omitir o resto com os `...`, apenas para legibilidade, confirmas?

Além disso, faz-me um pouco de confusão usar URIs como JSON keys. E incluísses no `_embedded` apenas as entradas mesmo, e cada uma teria o seu próprio `_links.self`? Acho que seria na mesma válido como HAL, mas é ligeiramente mais intuitivo para mim :sweat_smile:

Em particular, o `/._embedded.freguesias._links.https://.../rel/parent` (usando `/` como marcador da raiz do JSON) é redundante com o `/._links.self`, não? 🤔 E o mesmo com os links `/._embedded.freguesias._links.https://.../rel/freguesias/*`, seriam redundantes com os `/._embedded.freguesias.*._links.self`, se estou a perceber bem. Penso que isso foi referido numa das respostas no SO, mas não consegui seguir o raciocínio todo :sweat_smile:

**Comment by jfoclpf** [comment]
@waldyrious  isto foi sacado lá do exemplo do Stackoverflow mas eu também estou perdido, teria de ler as especificações do HAL.

**Comment by waldyrious** [comment]
Talvez usar o Ion em vez do HAL seja mais fácil de perceber?

https://geoapi.pt/municipios/Porto/freguesias seria algo do tipo

```jsonc
{
  "name": "Lista de frequesias do município do Porto",
  "self": { "href": "/municipios/Porto/freguesias" },
  "up": { "href": "/municipios/Porto" },
  "value": [
    {
      "name": "Bonfim",
      "self": { "href": "/municipios/Porto/freguesias/Bonfim" },
    },
    {
      "name": "Campanhã",
      "self": { "href": "/municipios/Porto/freguesias/Campanha" },
    }
    //...
  ]
}
```

Não sei se está correto, mas parece-me consistente com o exemplo "Example Paginated Collection Resource" em https://ionspec.org/#_example_collections

**Comment by waldyrious** [comment]
Ah, e já agora, nota que apesar de alguns endpoints terem hyperlinks no HTML (https://geoapi.pt/municipios/porto/freguesias de facto inclui links para os endpoints de cada freguesia), há muitos links em falta. Por exemplo https://geoapi.pt/municipios/porto/ não tem link para https://geoapi.pt/municipios/porto/freguesias, nem para https://geoapi.pt/distritos/porto (que não existe, mas a meu ver devia! :smile:)

Ou seja, além do JSON, o HATEOAS ainda precisa de trabalho a nível da representação HTML dos recursos para serem navegáveis e "descobríveis" :)

**Comment by jfoclpf** [comment]
bem visto, já agora, conheces algum linter para testar HAL ou HATEOS ou Ion?
Porque estar a desenvolver tudo isto sem qq feedback de validação, é um pouco assustador

**Comment by waldyrious** [comment]
Eu testei o exemplo que dei acima (que chamei "HAL válido") com o validador em https://jsonschema.dev, usando [este código](https://github.com/evently-cloud/hal-json-schema/blob/main/hal.json) como schema. O resultado é este: https://jsonschema.dev/s/aC0Em

**Comment by waldyrious** [comment]
Honestamente, comparando as opções acima, eu iria com o HAL. É mais explícito em relação aos links (separa-os do resto das propriedades) e pelo que percebi, é mais popular que o Ion.

**Comment by jfoclpf** [comment]
O https://jsonschema.dev/ testa apenas se o JSON é válido, referia-me a testar se o HAL é válido

**Comment by jfoclpf** [comment]
encontrei este projeto para validar HAL+JSON

https://github.com/deathbob/halidator

tens Ruby on Rails na tua máquina?

**Comment by waldyrious** [comment]
> O jsonschema.dev testa apenas se o JSON é válido, referia-me a testar se o HAL é válido

Not really :) no campo de texto à esquerda podes por um [JSON Schema](https://json-schema.org/) para um formato baseado em JSON (no caso do link que mandei acima, já está preenchido com um schema que define a sintaxe do HAL, que encontrei [aqui](https://github.com/evently-cloud/hal-json-schema/blob/main/hal.json)), e a ferramenta aplica esse schema ao JSON que puseres no lado direito. Ora tenta por exemplo colar no campo de texto à direita o exemplo que dei acima como "pseudo-HAL". É JSON válido, mas HAL inválido:

![image](https://user-images.githubusercontent.com/478237/194577581-c802b1e0-74c7-48a2-bed2-cefb9e4bc553.png)

**Comment by jfoclpf** [comment]
Ah, fixe, não tinha percebido! Muito obrigado! Espetáculo

Então este está válido:

```json
{
  "name": "Lista de freguesias do município do Porto",
  "_links": {
    "self": { "href": "/municipios/Porto/freguesias" },
    "up": { "href": "/municipios/Porto" }
  },
  "freguesias": [
    {
      "name": "Bonfim",
      "_links": { "self": { "href": "/municipios/Porto/freguesias/Bonfim" } }
    },
    {
      "name": "Campanhã",
      "_links": { "self": { "href": "/municipios/Porto/freguesias/Campanha" } }
    }
  ]
}
```

Agora a pergunta crítica: achas que conseguimos implementar esse HAL sem breaking changes, considerando que o resultado agora é este? Será que podemos ter na origem `nome` e um Array de `freguesias`?

```json
{
  "nome": "Porto",
  "freguesias": [
    "Bonfim",
    "Campanhã",
    "Paranhos",
    "Ramalde",
    "União das freguesias de Aldoar, Foz do Douro e Nevogilde",
    "União das freguesias de Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória",
    "União das freguesias de Lordelo do Ouro e Massarelos"
  ]
}
```

Se implementarmos o que sugeres, é uma "breaking change" e por isso ou teríamos que ir para um v2 e ter que adicionar a cada caminho um `/v2/`, ou ter alguma fé que ninguém dependa desta API de forma crítica, considerando que estamos apenas em fase de DEV. Ou então tentar mesclar a tua solução com a solução atual. 

Que te parece?

**Comment by jfoclpf** [comment]
Boas @waldyrious estive a investigar graças à tua dica do schema e baseando-me na tua resposta, sugiro esta solução, que te parece?

- É backward compatible
- Respeita aquele esquema que enviaste
- faz uso da key _embedded que acho que é para uma lista de links (vê [aqui](https://stackoverflow.com/a/73960099/1243247) e [aqui](https://stackoverflow.com/a/27424771/1243247))

```json
{
  "nome": "Porto",
  "descrição": "Lista de freguesias do município do Porto",
  "_links": {
    "self": { "href": "/municipios/Porto/freguesias" },
    "up": { "href": "/municipios/Porto" }
  },
  "freguesias": [
    "Bonfim",
    "Campanhã",
    "Paranhos",
    "Ramalde",
    "União das freguesias de Aldoar, Foz do Douro e Nevogilde",
    "União das freguesias de Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória",
    "União das freguesias de Lordelo do Ouro e Massarelos"
  ],
  "_embedded": {
    "freguesias": [
      {
        "nome": "Bonfim",
        "_links": { "self": { "href": "/municipios/Porto/freguesias/Bonfim" } }
      },
      {
        "nome": "Campanhã",
        "_links": { "self": { "href": "/municipios/Porto/freguesias/Campanha" } }
      }
    ]
  }
}
```

**Comment by waldyrious** [comment]
Pois, aqui tens duas opções, ou um output mais intuitivo, mas não retro-compatível, e portanto nova versão da API, ou manter a compatibilidade e ter um output menos intuitivo e mais redundante.

Eu pessoalmente estaria mais inclinado para o v2, já que isso não prejudica utilizadores atuais (que mantêm a mesma experiência) e permite que novos utilizadores tenham uma experiência mais user-friendly. Além disso, acho que alterações como #46 ficariam melhor numa v2 mais clean, do que numa v1 misturadas com a atual (ou seja, tendo duas formas de obter o mesmo resultado). Podes definir a v2 como uma versão HATEOAS-compatible via HAL, e também com os links no output HTML como mencionei acima, acho que isso justifica uma nova major version.

**Comment by jfoclpf** [comment]
é uma hipótese, mas iria dar muito mais trabalho, teria de criar caminhos novos para tudo, além disso #46 não tem qualquer problema pois é um caminho novo, não cria qualquer problema de incompatibilidade, confesso que estou na dúvida, a tua solução é mais limpinha, mas também acho que esta não é má (o ótimo é inimigo do bom ;)

```json
{
  "nome": "Porto",
  "descrição": "Lista de freguesias do município do Porto",
  "_links": {
    "self": { "href": "/municipios/Porto/freguesias" },
    "up": { "href": "/municipios/Porto" }
  },
  "freguesias": [
    "Bonfim",
    "Campanhã",
    "Paranhos",
    "Ramalde",
    "União das freguesias de Aldoar, Foz do Douro e Nevogilde",
    "União das freguesias de Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória",
    "União das freguesias de Lordelo do Ouro e Massarelos"
  ],
  "_embedded": {
    "freguesias": [
      {
        "nome": "Bonfim",
        "_links": { "self": { "href": "/municipios/Porto/freguesias/Bonfim" } }
      },
      {
        "nome": "Campanhã",
        "_links": { "self": { "href": "/municipios/Porto/freguesias/Campanha" } }
      }
    ]
  }
}
```

**Comment by waldyrious** [comment]
Claro, o projeto é teu, és tu quem tem o trabalho, por isso é só justo que a decisão seja tua :)

**Comment by jfoclpf** [comment]
Boas @waldyrious  não é uma questão da API ser minha, não a considero assim, de todo, isto é público e aberto e qualquer um pode contribuir, e tu por exemplo tens dado um contributo notável. A API é de todos e a prova disso é que qualquer um pode fazer um fork ;)

Queria apenas evitar um v2 para minimizar o esforço em código de programação e documentação e evitar também tornar os caminhos mais longos, encontrando contudo uma solução que respeitasse o HAL

**Comment by waldyrious** [comment]
Deparei-me hoje com este vídeo, [The Rest of ReST - Dylan Beattie](https://www.youtube.com/watch?v=g8E1B7rTZBI&t=250s), que explica muito bem um exemplo de como implementar uma REST API (incluindo HATEOAS) baseada em JSON. Penso que poderá ser útil/informativo para esta task :)

**Comment by jfoclpf** [comment]
muito bom o vídeo, vi todo, muito obrigado

**Comment by jfoclpf** [comment]
mas ele fala de imensos hypermedia standards o que me deixou mais confuso :)
como este: https://jsonapi.org/

**Comment by jfoclpf** [comment]
Vi o vídeo na totalidade que enviaste e na realidade no nosso caso bastaria ser

```json
{
  "nome": "Porto",
  "descrição": "Lista de freguesias do município do Porto",
  "_links": {
    "self": { "href": "/municipios/Porto/freguesias" },
    "up": { "href": "/municipios/Porto" },
    "freguesias": [
      {
        "nome": "Bonfim",
        "href": "/municipios/Porto/freguesias/Bonfim"
      },
      {
        "nome": "Campanhã",
        "href": "/municipios/Porto/freguesias/Campanha"
      }
    ]
  },
  "freguesias": [
    "Bonfim",
    "Campanhã",
    "Paranhos",
    "Ramalde",
    "União das freguesias de Aldoar, Foz do Douro e Nevogilde",
    "União das freguesias de Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória",
    "União das freguesias de Lordelo do Ouro e Massarelos"
  ]
}
```

Também passa a validação e é mais fácil de ler.

Que te parece?

**Comment by waldyrious** [comment]
Não tenho 100% de certeza. Por exemplo, convém confirmar se os nested links dentro do objeto `_links.freguesias` não precisariam também eles de ser wrapped em `_links.self`, como foi feito no primeiro exemplo d[este comentário](https://github.com/jfoclpf/geoapi.pt/issues/42#issuecomment-1271763421), para serem parsed como links no contexto do HAL; e também ver se faz mais sentido usar `_links.municipio` ou `_links.up`, já que o último é uma relação standard.

Mas à partida acho que é uma boa direção a ir.

**Comment by jfoclpf** [comment]
Mas achas que podemos ter `_links` dentro de `_links`? Ou seja `_links.freguesias[0]._links`?

**Comment by jfoclpf** [comment]
Considerando que para ser RESTful só falta a resposta HAL+JSON passo para #55
