### ISSUE TITLE
Suportar ?json=true além de ?json=1 no URL

### ISSUE THREAD

**Issue by waldyrious** [jfoclpf/geoapi.pt#47]
What the title says :)

**Comment by jfoclpf** [comment]
bem visto!

**Comment by jfoclpf** [comment]
se bem que true vai ser interpretado como string, mas é bem visto

**Comment by jfoclpf** [comment]
Feito com 4890cdb71f86991652dc197b27c3c98db93f2a62, ora vê
https://geoapi.pt/municipios/%C3%A9vora?json=true
Obrigado pela dica
