### ISSUE TITLE
Intersecção de Dados com Dados da PSP e GNR

### ISSUE THREAD

**Issue by ezefranca** [jfoclpf/geoapi.pt#49]
Vi [este comentário](https://www.reddit.com/r/devpt/comments/xvgqdb/comment/ir4yw9c/?utm_source=share&utm_medium=web2x&context=3) no Reddit e fui investigar um pouco.

Sobre a PSP, tem uma tabela completa, inclusive com mapa, fácil de extrair os dados.

https://www.psp.pt/Pages/onde-estamos.aspx?lang=pt

Já a GNR não encontrei os dados tão organizados

https://www.gnr.pt/unidades.aspx

**Comment by jfoclpf** [comment]
Olá @ezefranca 
isso apenas diz os locais das esquadras, não diz as áreas de atuação.
Estou certo?
