### ISSUE TITLE
Novo caminho /distritos/{distrito}/municipios

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/geoapi.pt#51]
Era isto a que te referias, não era @waldyrious ?

tipo `/distrito/porto/municipios`, para listar os municípios do distrito do Porto?

**Comment by waldyrious** [comment]
Ah, [neste comentário](https://github.com/jfoclpf/geoapi.pt/issues/42#issuecomment-1270841019)? Sim era isso.

Dito isso, agora pergunto-me se não faria sentido também haver o /distritos/porto para informação genérica sobre o distrito (NUTS, população, código INE, esse tipo de cenas).

**Comment by jfoclpf** [comment]
Dos recursos a que vou buscar (pasta `/res`), ainda não tenho informação sobre distritos, apenas municípios e freguesias, por isso posso tentar averiguar isso noutra issue

**Comment by jfoclpf** [comment]
Feito:

https://geoapi.pt/distritos/lisboa/municipios
