### ISSUE TITLE
Como aceder pelo endereço/ip externo?

### ISSUE THREAD

**Issue by joaocps** [jfoclpf/geoapi.pt#54]
Há alguma forma de fazer o acesso á API, após lançar a API localmente, quer seja em modo de produção ou não, pelo endereço externo? Por exemplo, http://89.115.200.11:5000/gps?lat=40.153687&lon=-8.514602&detalhes=1&json=1.

@jfoclpf

**Comment by joaocps** [comment]
Tinha a firewall mal configurada, foi resolvido e funciona.

**Comment by jfoclpf** [comment]
também podes usar o caminho mais bonito 

http://89.115.200.11:5000/40.153687,-8.514602/detalhes?json=1.
