### ISSUE TITLE
Usar elemento `<details>` para colapsar listas extensas no output HTML

### ISSUE THREAD

**Issue by waldyrious** [jfoclpf/geoapi.pt#57]
Para listagens muito extensas (por exemplo os dados dos censos do INE introduzidos em #53), dá jeito poder colapsá-las com o uso do elemento `<details>`, que implementa essa funcionalidade nativamente nos browsers (sem necessidade de JavaScript).

Exemplo:

```html
<details>
  <summary>Conteúdo colapsado:</summary>
  <ul>
    <li>um</li>
    <li>dois</li>
    <li>três</li>
  </ul>
</details>
```
Resultado: 

<details>
  <summary>Conteúdo colapsado:</summary>
  <ul>
    <li>um</li>
    <li>dois</li>
    <li>três</li>
  </ul>
</details>

**Comment by jfoclpf** [comment]
Boa ideia
neste momento os objetos JSON estão a ser expandidos numa tabela html/bootstrap [aqui](https://github.com/jfoclpf/geoapi.pt/blob/main/src/server/utils/hbsHelpers.js) para apresentação html. Terei de ver como integrar isso, pois não estou a ver como integrar a tag `<details>` dentro de uma tabela, mas é uma boa ideia. Talvez criando outra tabela separada dentro dessa tag.

**Comment by jfoclpf** [comment]
que te parece agora @waldyrious ?

https://geoapi.pt/municipios/%C3%A9vora

este tem vários "nested elements" e renderiza ok
https://geoapi.pt/gps/40.153687,-8.514602/detalhes

**Comment by jfoclpf** [comment]
acho que está bem agora, se achares que pode haver melhorias, abro o tópico

mais uma vez obrigados pelo retorno

**Comment by waldyrious** [comment]
Ficou muito fixe! Nice work:)
