### ISSUE TITLE
Aplicar limitador apenas para os endpoints da API, excetuando o index e static assets

### ISSUE THREAD

**Issue by joao** [jfoclpf/geoapi.pt#58]
@jfoclpf, estive um bocado desligado no último mês e estava agora a acompanhar os issues em que sou mencionado.

Está a dar-me um erro de `Too many requests, please try again later.`, quando tendo aceder a qualquer página no geoapi.pt. Tenho consciencia que existe um limite de 100 pedidos por 15 minutos, mas no máximo terei visitado 10 páginas/endpoints.  

Será que o limite também está a ser aplicado a assets que sejam pedidos, ao retornar uma página e não somente a visitas de um determinado URL?  

Adicionalmente, talvez fosse melhor excluir a homepage dos limites, ou pelo menos aumentar para as páginas estáticas, de modo a que um utilizador que não esteja consciente do limite de 100 pedidos encontrar a documentação em que tal é mencionado: 
   
![screenshot 2022-11-03 at 15 19 09](https://user-images.githubusercontent.com/1041/199761349-f5c1c353-e046-4cba-935e-f209f598e59b.png)

**Comment by jfoclpf** [comment]
Olá João, tudo bem? Sê bem-vindo ;)

Isso que reportas de facto é estranho.

A API usa este limitador
https://www.npmjs.com/package/express-rate-limit

Não estás a usar esse IP para fazer outros pedidos?

**Comment by joao** [comment]
Obrigado! :)

Estava somente a navegar no website, e experimentar os endpoints de exemplo, num IP residencial. Não consegui reproduzir agora o que aconteceu.

Indo às developer tools do browser consigo ver que uma visita à homepage são 9 pedidos ao geoapi.pt para serem devolvidos pelo serviço 'express'. 1 visita com 9 pedidos conta como 1 ou 9 para o rate limiting?

![screenshot 2022-11-03 at 19 11 34](https://user-images.githubusercontent.com/1041/199813431-be55749a-7957-489f-8d99-1062753c8074.png)

Possivelmente foi só algum edge-case, já que tentei reproduzir fazendo disable da cache do browse e refresh.

Já agora: além do limite de 100 pedidos, há algum intervalo de tempo entre eles que dispare o limite mais cedo? É que quando aconteceu-me o 'rate-limiting' eu realmente carreguei em alguns links rapidamente para abrir em novas 'tabs'.

**Comment by jfoclpf** [comment]
Bem visto, de facto penso que conta como 9 pedidos e não apenas 1. Acho que tenho que restringir o limitador apenas para alguns endpoints, tal é possível.

Sim, há uma janela temporal 

````js
      windowMs: 15 * 60 * 1000, // 15 minutes 
       max: 15 * 60, // Limit each IP to average 1 request/sec
````

Na realidade o limite neste momento é 15*60 pedidos ao longo de 15 minutos, ou seja, uma média de 1/segundo.

**Comment by joao** [comment]
Expliquei-me mal, referia-me a por exemplo abrir 6 URLs no espaço de 4s, isso dispararia o rate-limiting?  

É que possivelmente terei feito isso, indo à homepage e carregando em links rapidamente para abrir em novas 'tabs' de modo a ver o output.  

O código realmente menciona um 'average', mas talvez não o seja e eu tenha disparado o bloqueio. Mesmo assim não consigo fazer com que fique de novo bloqueado. Deve ter sido somente um edge-case, obrigado pela tua atenção em procurar fazer o debug, mas podes fechar o issue e não perder mais tempo. Se voltar a surgir aviso!

**Comment by jfoclpf** [comment]
Acho que se clicares rapidamente em links não vai disparar, porque o cálculo é feito apenas numa janela de 15 minutos (os últimos 15 minutos).

Em vou deixar o assunto aberto em qualquer caso, porque evocaste um ponto importante, não tem lógica o index e os static assets (ficheiros css, js, imagens, etc.) terem limitador, o limitador faz sentido apenas para os endpoints da API, para evitar abusos e raspagem (scraping).

**Comment by jfoclpf** [comment]
Já vi como resolver, tenho que editar [aqui](https://github.com/jfoclpf/geoapi.pt/blob/main/src/server/index.js#L135), para:

```js
// Create the rate limiting middleware
let limiter
if (argvOptions.rateLimit) {
  limiter = rateLimit({
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: 15 * 60, // Limit each IP to average 1 request/sec
    standardHeaders: true, // Return rate limit info in the `RateLimit-*` headers
    legacyHeaders: false // Disable the `X-RateLimit-*` headers
  })
}

//....

try {
  fs.readdirSync(expressRoutesDir).forEach(filename => {
    const router = require(path.join(expressRoutesDir, filename))
    const routeFn = (req, res, next) => {
      router.fn(req, res, next, { administrations, regions, appRootPath: appRoot.path, gitProjectUrl })
    })
    if (argvOptions.rateLimit) {
       app.get(router.route, limiter, routeFn)
    } else {
       app.get(router.route, routeFn)
    }
    debug(`Loaded express get route from ${filename} with route ${router.route}`)
  })
```

**Comment by joao** [comment]
Vendo isso código deu para ver como verificar no browser o 'rate-limiting', indo aos 'Headers' nas 'Developer Tools':  

![screenshot 2022-11-04 at 15 09 10](https://user-images.githubusercontent.com/1041/200009392-a3104c0a-3a17-4d12-be80-5e4f32651097.png)

**Comment by jfoclpf** [comment]
Super interessante, desconhecia que ele enviava cabeçalhos com essa informação

**Comment by jfoclpf** [comment]
resolvido com 455cdc223626ca3a99cbf4bab257daf9c638f9e8
