### ISSUE TITLE
retornar JSON também com o host `json.geoapi.pt`

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/geoapi.pt#59]
@waldyrious e @joao 

Neste momento a API retorna JSON quando

 - tem o parâmetro GET `json=1`, ex: `/municipios/évora?json=1`
 - o pedido tem no cabeçalho HTTP `Accept: application/json`

Estava a pensar também adicionalmente um host `json.geoapi.pt`, ex: `https://json.geoapi.pt/gps/40.153687,-8.514602`

Que vos parece a ideia?

**Comment by joao** [comment]
A nível de endpoints de API penso que o mais comum são estas duas situações:
- um subdominio api.dominio.com, 
- o URL terminar com um .json

Como o projecto já tem 'api' no nome, suponho que um subdominio com esse termo fique estranho.

Penso que para não complicar pode ficar como já está agora.

**Comment by jfoclpf** [comment]
obrigado pelas ideias @joao 

 o que queres dizer com um URL com um .json? Referes-te a um TLD? Não existe nenhum TLD para .json

**Comment by joao** [comment]
@jfoclpf refiro-me à convenção habitual, em frameworks como Rails, de retornar JSON quando tendo uma extensão `.json`.

Exemplo, a versão HTML é:  
`https://geoapi.pt/municipios`
e a JSON seria:
`https://geoapi.pt/municipios.json`

A origem desta convenção é os URLs originalmente, e ainda hoje em muitos casos, terminarem com extensões `.html`, então para obter um JSON a lógica é substituir-se (ou acrescenta-se, porque agora está em desuso utilizar a extensão `.html`) tal por `.json`.  

Contudo, o `?json=1` actual já cumpre esta função.

**Comment by jfoclpf** [comment]
@joao super interessante, de facto não me lembrava dessa convenção

mas tens razão, não vale a pena aumentar a entropia, obrigado pelo retorno

**Comment by waldyrious** [comment]
Embora concorde que a solução atual do `?json=1` seja suficiente, não vejo porque não implementar também as alternativas de usar um subdomínio `json.geoapi.pt` e de usar o sufixo `.json` (sem desativar a funcionalidade existente, claro). Podem ser mais práticas dependendo do caso de uso.

**Comment by jfoclpf** [comment]
sim, e tal é muito fácil de fazer, basta ler `req.hostname`

http://expressjs.com/en/api.html#req.hostname

**Comment by waldyrious** [comment]
Por curiosidade, qual é a dificuldade/complexidade com o `.json`? Posso estar a ver as coisas de forma naive, mas não daria para fazer string match no final do URL?

**Comment by jfoclpf** [comment]
Olá @waldyrious 
permitir um .json obrigaria a alterar todas funções "routes", porque por exemplo /municipios/evora.json já não activaria a função que é espoletada quando se chama /municipios/evora

**Comment by jfoclpf** [comment]
feito, ora vede

 - https://json.geoapi.pt/cp/2495-300
 - https://json.geoapi.pt/municipios/guimar%C3%A3es/freguesias/serzedelo
