### ISSUE TITLE
Municipio em falta

### ISSUE THREAD

**Issue by vikcch** [jfoclpf/geoapi.pt#61]
No distrito de Faro não consta o município _Lagoa_

https://geoapi.pt/distritos/municipios

**Comment by jfoclpf** [comment]
Obrigado por teres reportado, é um bug do ficheiro original da DGAL

Normalmente os municípios têm sempre o campo distrito, ora vê

https://geoapi.pt/municipios/lagos

https://geoapi.pt/municipios/albufeira

Mas o de Lagoa estranhamente não tem

https://geoapi.pt/municipios/lagoa

Vou ter que adicionar manualmente

**Comment by jfoclpf** [comment]
Muito obrigado

Podes sff fazer PR diretamente na fonte?

https://github.com/jfoclpf/geoapi.pt/blob/main/res/details-parishes-municipalities/detalhesMunicipiosB.json

Esse ficheiro pode ser editado e alterado.

Obrigado

**Comment by jfoclpf** [comment]
Espera, parece que o ficheiro original está mesmo correcto, é qualquer coisa com o código mesmo, tenho que ver com mais calma

**Comment by jfoclpf** [comment]
Boas @vikcch 

isto deu muito mais trabalho que imaginava, estive o dia todo nisto, ora vê os commits aí em cima, mas acho que já está.

Havia uma enorme divergência na nomenclatura das fontes, por exemplo ` Lagoa,  Lagoa (Algarve), Lagoa (São Miguel), Lagoa (Açores)`, enfim, um caos. E isto apenas para Lagoa. O ideal seria usar o código do INE, mas nem todas as fontes o têm.

Enfim, acho que agora está bem, por favor confirma se detectas agora algum erro.

Ficámos com apenas `Lagoa` e `Lagoa (Açores)`
 - https://geoapi.pt/municipios/lagoa
 - https://geoapi.pt/municipios/lagoa%20(a%C3%A7ores)

O distrito de Faro já apresenta também os municípios correctos

https://geoapi.pt/distritos/faro/municipios

Lagoa nos Açores também aparece aqui:
https://geoapi.pt/distritos/r.%20a.%20a%C3%A7ores/municipios

Podes sff confirmar que agora está tudo bem?

muito obrigado

**Comment by jfoclpf** [comment]
se ainda encontrares algum bug, eu fecho o _issue_

mas por favor testa, para ver se agora está tudo bem. Também corrigi `'lagoa','madalena','nordeste','povoação','praia da vitória','ribeira brava','são joão da pesqueira','velas'` mas pf testa tu também

obrigado

**Comment by jfoclpf** [comment]
@vikcch confirmas que o problema ficou resolvido?
