### ISSUE TITLE
Formato das coordenadas no HTML

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/geoapi.pt#63]
> Entretanto, se me perdoarem a preguiça de abrir um issue separado, posso sugerir que, no output HTML, as coordenadas sejam formatadas com graus, minutos e segundos, em vez de no formato decimal? Isto porque esse formato já está presente quer no URL, quer no texto de título, pelo que é redundante:

![image](https://user-images.githubusercontent.com/478237/202928201-2d3ec583-f1ee-42b2-8799-c1769e961977.png)

_Originally posted by @waldyrious in https://github.com/jfoclpf/geoapi.pt/issues/60#issuecomment-1321252803_

**Comment by jfoclpf** [comment]
Olá @waldyrious 

Obrigado pela sugestão, contudo tenho algumas reservas porque acho que vai aumentar a entropia visto que todas as coordenadas estão em valores decimais em todas as fontes (ficheiros de base na pasta `/res`) e todos os processamentos.

Além disso o HTML é suposto refletir o resultado em JSON.

**Comment by jfoclpf** [comment]
Vendo bem, acho que tens razão, pois aqueles valores não refletem ipsis verbis qualquer valor do pedido GET nem qualquer valor da resposta JSON e por isso podem ser o que quisermos.

Vou alterar, é aqui
https://github.com/jfoclpf/geoapi.pt/blob/main/src/server/routes/gps.js#L202

Tenho apenas que encontrar uma função que faça a conversão de decimal para graus e minutos

**Comment by waldyrious** [comment]
Nice 🙂 obrigado pela implementação rápida! 💪

**Comment by jfoclpf** [comment]
Eu é que agradeço a dica ;)
