### ISSUE TITLE
Códigos postais mostram popup vazio ou "undefined"

### ISSUE THREAD

**Issue by waldyrious** [jfoclpf/geoapi.pt#66]
Não se se é suposto poder-se ver alguma informação quando se clica nas bolinhas vermelhas que representam instâncias individuais de códigos postais, mas elas são de momento clicáveis e mostram um popup, só que o conteúdo é vazio ou "undefined". Por exemplo:

https://geoapi.pt/cp/4960 👇️

![image](https://user-images.githubusercontent.com/478237/209657712-32430b00-3978-496d-b351-ba03fcf4d929.png)

https://geoapi.pt/cp/4960-110 👇️

![image](https://user-images.githubusercontent.com/478237/209657665-4f655b5b-1569-4930-ba02-8558b00e416f.png)

**Comment by jfoclpf** [comment]
@waldyrious obrigado mais uma vez´

o problema está aqui
https://github.com/jfoclpf/geoapi.pt/blob/main/src/public/src/js/routes/postalcode.js#L60

Só posso fazer `bindPopup` quando a info está disponível 

substituir 

```js
ponto.bindPopup(`${el.rua}${el.casa ? ', ' + el.casa : ''}`)
```

por 

```js
if (el.rua) {
  ponto.bindPopup(`${el.rua}${el.casa ? ', ' + el.casa : ''}`)
}
```

**Comment by jfoclpf** [comment]
resolvido!

**Comment by jfoclpf** [comment]
Bem visto @waldyrious 

usar interactive para ´false´

https://leafletjs.com/reference.html#circle-interactive

no ´L.polygon´ e ´L.circle´

**Comment by jfoclpf** [comment]
já está resolvida essa segunda questão, mais qq coisa diz @waldyrious

**Comment by waldyrious** [comment]
Ficou excelente, thanks!
