### ISSUE TITLE
Dados de censos 2021, APIs externas e demora do pedido

### ISSUE THREAD

**Issue by joaocps** [jfoclpf/geoapi.pt#68]
Boas novamente @jfoclpf !
Antes de mais quero agradecer por todo o trabalho que têm feito !
Vão adicionar os dados dos censos 2021 da mesma forma/complexixade como adicionaram o dos censos 2011?

Grande abraço

**Comment by jfoclpf** [comment]
Olá @joaocps 
obrigado pelo apoio
essa limitação advém do próprio INE, cujos censos 2021 ainda não têm a info toda completa
Sacámos a info daqui: https://mapas.ine.pt/download/index2011.phtml

**Comment by joaocps** [comment]
Obrigado pela rápida resposta @jfoclpf ! Ainda não tive muito tempo para explorar a forma como obtem os dados dos ficheiros gpkg mas na altura pareceu-me que o ficheiro referente a 2021 já tinha mais dados referentes ás diferentes divisões administrativas 👍 

Outra questão, agora com a adição de todos estes novos dados os requests tornaram-se mais demorados. Se eu incluir o codigoINE no request simples (sem detalhes) vais agilizar o processo? Compensa-me criar um endpoint apenas para essa conversão(lat/lon para CodigoINE) de modo a diminuir o tempo de resposta?

Mais uma vez muito obrigado!

**Comment by joaocps** [comment]
![image](https://user-images.githubusercontent.com/23501993/212030797-d55d0d2f-81fb-4c9e-a616-075dd32f039c.png)

http://mylocalnetworkip:8080/gps/40.465021,-8.456376?detalhes=1&json=1

A diferença do tempo de resposta é de 50ms para 450/500ms 😃

**Comment by jfoclpf** [comment]
> Obrigado pela rápida resposta @jfoclpf ! Ainda não tive muito tempo para explorar a forma como obtem os dados dos ficheiros gpkg mas na altura pareceu-me que o ficheiro referente a 2021 já tinha mais dados referentes ás diferentes divisões administrativas 👍

Só se já atualizaram, na altura quando obtive os dados para 2021, tinham apenas pouca informação, mas posso reverificar.
Podes confirmar tu próprio se os ficheiros gpkg 2021 têm mais informação?

> Outra questão, agora com a adição de todos estes novos dados os requests tornaram-se mais demorados. Se eu incluir o codigoINE no request simples (sem detalhes) vais agilizar o processo? Compensa-me criar um endpoint apenas para essa conversão(lat/lon para CodigoINE) de modo a diminuir o tempo de resposta?

Esse é um problem que tenho pensado. Está demorado não é por isso, é porque em certas situações ele vai buscar dados a outras APIs (Open Street Maps, para o nome da rua ou número de porta, por exemplo) e [Open-Elevation API](https://open-elevation.com/) para a altitude (quando não consegue detectar fazendo uso dos dados da DGE).

A solução poderia ser criar um query parameter onde o recurso a essas APIs não é feito, por exemplo /gps/40.465021,-8.456376?detalhes=1&noExtApi=1&json=1

> Mais uma vez muito obrigado!
De nada, sempre às ordens

**Comment by waldyrious** [comment]
Perdoem-me mandar o bitaite, mas a minha primeira impressão é que faz mais sentido o comportamento padrão ser rápido e auto-suficiente (não dependente de outras APIs), e informação adicional ser opt-in através de parâmetros (`?extApi=1`) ou endpoints específicos (como já é o caso com o `/detalhes` nas paths de `/gps`). Usar parâmetros negativos como `noExtApi=1` normalmente é desencorajado em termos de usabilidade (é o mesmo que `foo != false` vs `foo == true`, ou duplas negativas em termos de escrita — cria um pequeno "soluço mental" que é evitável).

De qualquer forma, penso que seria benéfico que a abordagem fosse uniforme (query parameter ou sufixo no URL) através de toda a API, por uma questão de discoverability.

**Comment by jfoclpf** [comment]
Boas @waldyrious não tens que perdoar nada, as tuas opiniões são sempre bem acolhidas :) 

O problema é que sem estas APIs externas há casos onde não conseguimos extrair o nome da rua ou o número de porta ou a altitude e acho que estas dados devem ser fornecidos por padrão. Deve ser o _default behaviour_ IMHO.

Para evitar a dupla negação, que te parece então um query parameter com `extApi=0` ou `extApi=false`?

Em qualquer caso estou a pensar adicionar um endpoint com um sufixo `/curto` (tradução manhosa de _short_, mas gostaria de ouvir opiniões) (ex: `/gps/40.465021,-8.456376/curto`) onde por questões de eficiência e tempo de resposta a API retorna apenas o distrito, município e a freguesia. 

Que te parece?

**Comment by jfoclpf** [comment]
Mas repara que são objetivos diferentes

 - `extApi=0` é uma flag que serviria apenas para dizer: não uses API externas (a API só usa API externas em algumas situações específicas quando não consegue obter dados localmente)
 - sufixo `/curto` (sugeres outro?): dá-me apenas distrito, município e a freguesia

São coisas distintas e não mutuamente exclusivas

**Comment by joaocps** [comment]
@jfoclpf A mim parece-me bem ! Deve haver possibilidade de não utilização de api externas. Em relação ao sufixo, também me parece bem escolhido, curto ou base são opções ! 👍

**Comment by jfoclpf** [comment]
@joaocps obrigado pela dica, `/base` também me parece bem

**Comment by jfoclpf** [comment]
Caros, já está, digam de vossa justiça

Novos endpoints:
- https://geoapi.pt/gps/38.748406,-9.102984/base
- https://geoapi.pt/gps/38.748406,-9.102984/base/detalhes

Flag para não usar api externas (`ext-apis=0`):
 - https://geoapi.pt/gps/38.74059476166391,-9.112448383609724?ext-apis=0
Se repararem nestes casos, quer a altitude, quer a rua quer o código postal, umas vezes dá, outras vezes não dá. Podem arrastar o ponto no mapa para testarem

Que vos parece? Sugestões!

**Comment by jfoclpf** [comment]
@waldyrious e @joaocps , ideias?

@joaocps esta solução era o que querias? Está mais rápido? Podes sff testar agora o tempo de resposta a vários pedidos, como fizeste anteriormente?

**Comment by joaocps** [comment]
Boas @jfoclpf !
Parece-me tudo bastante bem, vou testar entretanto com diversos requests e mando feedback! Entretanto vou atualizar os ficheiros dos censos 2021 porque realmente foram atualizados pelo ine e já se encontram com a mesma complexidade dos de 2011.
Há primeira vista parece-me que a velocidade aumentou bastante, mas nada que um teste mais intensivo não venha a tirar as duvidas 😎

**Comment by jfoclpf** [comment]
@joaocps fixe, achas que consegues fazer um PR com os novos ficheiros do INE para 2021?

**Comment by joaocps** [comment]
> @joaocps fixe, achas que consegues fazer um PR com os novos ficheiros do INE para 2021?

Feito!

**Comment by jfoclpf** [comment]
@jfoclpf já aceitei o PR e já consegui resolver o problema do unzip. Já executei o script e parece estar a funcionar.

Contudo dá erro em alguns (poucos) ficheiros para 2021, que não consigo perceber mesmo de onde vem o erro.

Por exemplo em `BGRI2021_4801.gpkg` e `BGRI2021_4802.gpkg` dá este erro:
`Error parsing Geometry Error: Unable to detect CRS, GeoJSON has no "crs" property.`

Acho que está relacionado com os códigos estranhos para o CRS do grupo Ocidental dos Açores

**Comment by jfoclpf** [comment]
@joaocps os dados censos 2021 já estão disponíveis, exemplos:

 - https://geoapi.pt/municipio/porto/freguesia/campanh%C3%A3
 - https://geoapi.pt/municipio/porto
 - https://geoapi.pt/gps/38.748406,-9.102984/detalhes

**Comment by jfoclpf** [comment]
@joaocps para que a apresentação text/html fica mais user friendly, achas que podes fazer um mapa entre os códigos e os termos "full text"? Please!

```


N_EDIFICIOS_CLASSICOS | 1490
-- | --
N_EDIFICIOS_CLASS_CONST_1_OU_2_ALOJ | 442
N_EDIFICIOS_CLASS_CONST_3_OU_MAIS_ALOJAMENTOS | 1033
N_EDIFICIOS_EXCLUSIV_RESID | 1426
N_EDIFICIOS_1_OU_2_PISOS | 605
N_EDIFICIOS_3_OU_MAIS_PISOS | 885
N_EDIFICIOS_CONSTR_ANTES_1945 | 292
N_EDIFICIOS_CONSTR_1946_1980 | 646
N_EDIFICIOS_CONSTR_1981_2000 | 445
N_EDIFICIOS_CONSTR_2001_2010 | 95
N_EDIFICIOS_CONSTR_2011_2021 | 12
N_EDIFICIOS_COM_NECESSIDADES_REPARACAO | 725
N_ALOJAMENTOS_TOTAL | 16810
N_ALOJAMENTOS_FAMILIARES | 16796
N_ALOJAMENTOS_FAM_CLASS_RHABITUAL | 14104
N_ALOJAMENTOS_FAM_CLASS_VAGOS_OU_RESID_SECUNDARIA | 2669
N_RHABITUAL_ACESSIVEL_CADEIRAS_RODAS | 6825
N_RHABITUAL_COM_ESTACIONAMENTO | 2379
N_RHABITUAL_PROP_OCUP | 6351
N_RHABITUAL_ARRENDADOS | 7052
N_AGREGADOS_DOMESTICOS_PRIVADOS | 14132
N_ADP_1_OU_2_PESSOAS | 8253
N_ADP_3_OU_MAIS_PESSOAS | 5879
N_NUCLEOS_FAMILIARES | 10548
N_NUCLEOS_FAMILIARES_COM_FILHOS_TENDO_O_MAIS_NOVO_MENOS_DE_25 | 4802
N_INDIVIDUOS | 35479
N_INDIVIDUOS_H | 16598
N_INDIVIDUOS_M | 18881
N_INDIVIDUOS_0_14 | 4698
N_INDIVIDUOS_15_24 | 3751
N_INDIVIDUOS_25_64 | 18489
N_INDIVIDUOS_65_OU_MAIS
```
Por exemplo `N_INDIVIDUOS_65_OU_MAIS` -> `Nr. de Indivíduos com 65 ou mais anos`

Para adicionar aqui: https://github.com/jfoclpf/geoapi.pt/blob/main/src/server/utils/adaptObjForHtmlRes.js#L24

**Comment by jfoclpf** [comment]
@waldyrious  achas que podes dar uma mãozinha ? ;)

**Comment by waldyrious** [comment]
> @waldyrious achas que podes dar uma mãozinha ? ;)

Comentei no #70, que pelo que percebi foi ramificado a partir deste issue para manter os tópicos separados, e para se poder fechar este.
