### ISSUE TITLE
CodigosINE incorretos

### ISSUE THREAD

**Issue by joaocps** [jfoclpf/geoapi.pt#72]
Boa tarde mais uma vez @jfoclpf ! Qual a forma de dar update a estes valores de codigo ine? Penso que não estejam atualizados ... 

![image](https://user-images.githubusercontent.com/23501993/213252591-a61a49dd-0799-4fd8-a556-5c2437af5650.png)

**Comment by jfoclpf** [comment]
boas @joaocps esse código INE está correcto, é o chamado código alfanumérico do INE, ora vê:

https://github.com/jfoclpf/geoapi.pt/blob/main/res/censos/data/freguesias/0302FA.json

https://www.ine.pt/xportal/xmain?xpid=INE&xpgid=ine_cont_inst&INST=6251013&xlang=pt

**Comment by jfoclpf** [comment]
os primeiros 2 dígitos são o distrito, depois os 2 seguintes o município e os 2 últimos a freguesia

**Comment by joaocps** [comment]
Sim eu sei que é o código do INE , mas pensei que os últimos dois algarismos (FF) fossem sempre numéricos! Estou confuso com esse FA ...

**Comment by jfoclpf** [comment]
Barcelos tem uma data de freguesias
https://geoapi.pt/municipios/barcelos/freguesias
eles devem ter criado esses códigos com a reforma das freguesias, se reparares é tudo freguesias recentes, esses códigos acho que vêm do GeoJSON da Direção Geral do Território (carta administrativa)

**Comment by jfoclpf** [comment]
esses códigos acho que vêm [daqui](https://github.com/jfoclpf/geoapi.pt/blob/main/res/portuguese-administrative-chart/Cont_AAD_CAOP2020.zip) que por sua vez vêm daqui: https://www.dgterritorio.gov.pt/dados-abertos (procurar por 2020)

O ficheiro (carta administrativa) é o de 2020, já existe para 2021, se quiseres ver se estão atualizados e dar um update, a malta agradece ;)

Basta seguir as instruções [aqui](https://github.com/jfoclpf/geoapi.pt/tree/main/res#carta-administrativa-oficial-de-portugal).

**Comment by joaocps** [comment]
Vou dar uma vista de olhos @jfoclpf 👍

**Comment by jfoclpf** [comment]
@joaocps Estive a confirmar e esse valor vem [daqui](https://github.com/jfoclpf/geoapi.pt/blob/main/src/server/services/getRegionsAndAdmins.js#L233).

O ficheiro da DGT (CAOP 2020) chama-lhe `DICOFRE`

Encontrei também isto [aqui](https://dados.gov.pt/pt/datasets/carta-administrativa-oficial-de-portugal-caop2021-ram/):

> A CAOP [Carta Administrativa Oficial de Portugal] regista o estado de delimitação e demarcação das circunscrições administrativas do País, ou seja, os limites oficiais de distrito, concelho e freguesia (estes limites têm igualmente correspondência com as NUTS I, NUTS II e NUTS III, de acordo com a Lei n.º 75/2013 de 12 de setembro). A sua elaboração e conservação é uma das atribuições da Direção-Geral do Território, nos termos do disposto na alínea l) do nº 2 do artigo 2º do Decreto Regulamentar nº 30/2012 de 13 de março, **sendo que a atribuição do código unívoco de cada freguesia (DICOFRE) é da responsabilidade do Instituto Nacional de Estatística**. 

O ficheiro da CAOP para 2021 está [aqui](http://mapas.dgterritorio.pt/ATOM-download/CAOP-Cont/2021/Cont_AAD_CAOP2021.zip
), é uma questão de verificar se se mantém, mas julgo que sim.

**Comment by jfoclpf** [comment]
Confirma-se @joaocps verifiquei agora e no ficheiro de 2021 essa freguesia tem também esse código DICOFRE

![image](https://user-images.githubusercontent.com/3984909/213422364-d635464a-3213-4d7b-99a1-eafb45768921.png)

**Comment by jfoclpf** [comment]
Mais uma confirmação, ora vê:
https://www.artigosenoticias.com/freguesia/0302FA/

Vou fechar o issue @joaocps e vou abrir outro para a atualização da CAOP 2021
