### ISSUE TITLE
Atualizar a CAOP para 2021

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/geoapi.pt#73]
A CAOP 2021 já está disponível [aqui](http://mapas.dgterritorio.pt/ATOM-download/CAOP-Cont/2021/Cont_AAD_CAOP2021.zip) (esta API ainda usa a de 2020)

Atualizar em conformidade.

**Comment by jfoclpf** [comment]
feito

**Comment by joaocps** [comment]
Boas @jfoclpf ! Desculpa ter lançado a outra issue e depois não voltei a entrar em contacto contigo ... Andei cheio de trabalho nestes dias e com alguns contratempos acabou por ser impossivel ! 

De qualquer forma excelente trabalho !
