### ISSUE TITLE
Problema ao selecionar freguesias

### ISSUE THREAD

**Issue by fgbg03** [jfoclpf/geoapi.pt#77]
Quando seleciono uma freguesia no site sou automaticamente redirecionado para a página da freguesia pré-selecionada. O que na prática só permite ver dados da primeira freguesia por ordem alfabética de cada município. Se interessar utilizei o Firefox

**Comment by jfoclpf** [comment]
boas fabio, podes dar mais exemplos específicos com links sff?

**Comment by jfoclpf** [comment]
ah, espera @fgbg03 acho que já percebi

**Comment by jfoclpf** [comment]
@fgbg03 já está resolvido, se encontrares novamente o erro diz sff
