### ISSUE TITLE
Desativar duplo-clique para zoom no mapa

### ISSUE THREAD

**Issue by waldyrious** [jfoclpf/geoapi.pt#78]
Já que o duplo clique é usado para abrir links de áreas delimitadas do mapa (distritos, municípios, etc.), seria melhor que esse evento não resultasse também num zoom do mapa, já que se torna um pouco confuso o que está a acontecer. Aliás, isso até pode causar erros de seleção, porque o mapa ao fazer zoom altera a posição geográfica por baixo do cursor — por exemplo, na página inicial tentei fazer duplo-clique na área do distrito de Braga, mas como o zoom fez kick-in a meio do duplo-clique, acabei por abrir foi o distrito de Viana do Castelo! :sweat_smile:

Havendo já a possibilidade de fazer zoom com o botão `➕` e mouse scroll, acho que não ficaria nenhuma funcionalidade prejudicada se isto fosse implementado.

**Comment by waldyrious** [comment]
Adicionalmente, seria fixe se a área delimitada mudasse ligeiramente quando fosse duplo-clicada (por exemplo um border color diferente, ou um background mais escurecido), já que o carregamento da página seguinte não é instantâneo, e assim dava a entender que a ação foi reconhecida. Mas isso é apenas um nice to have :)

**Comment by jfoclpf** [comment]
Obrigado pelo retorno @waldyrious 
Vou fazê-lo ASAP

**Comment by jfoclpf** [comment]
@waldyrious já está operacional, diz-me se te parece bem

se achares que ainda não está bem, volto a abrir o issue

**Comment by waldyrious** [comment]
Hm, continuo a ter o mesmo problema:

![ZgY52h6jq0](https://user-images.githubusercontent.com/478237/236669037-11045d40-ead7-49e7-86af-d2ee437b504d.gif)

**Comment by jfoclpf** [comment]
Podes ser mais especifico? O distrito que abre é o distrito que clicas,
certo?

**Comment by waldyrious** [comment]
Sim, mas o problema descrito neste issue (o mapa fazer zoom quando se faz duplo-clique) continua a acontecer. Pensei que era a isso que te referias quando mencionaste que o fix estava operacional, talvez então percebi mal?

**Comment by jfoclpf** [comment]
O problema se bem te lembras era outro: quando fazias duplo-clique no mapa, ele fazia primeiro zoom, desviava, e só depois abria o link, podendo até ser no distrito errado.

Cito-te ;)

> Aliás, isso até pode causar erros de seleção, porque o mapa ao fazer zoom altera a posição geográfica por baixo do cursor — por exemplo, na página inicial tentei fazer duplo-clique na área do distrito de Braga, mas como o zoom fez kick-in a meio do duplo-clique, acabei por abrir foi o distrito de Viana do Castelo! sweat_smile

O zoom para clique é importante, e se reparares agora quando fazes duplo-clique ele já não desvia

**Comment by waldyrious** [comment]
Lol ok, foi problema de comunicação. Mea culpa por ter escrito demasiado :sweat_smile: a chave aqui é o "aliás" e o "até" — essa parte da frase foi mais um adendo ao que eu tinha escrito antes, mas deixei-me levar e acabou por ficar mais extenso e dar a impressão de que era esse o problema que eu pretendia reportar.

O meu foco com o issue era de facto o facto de haver zoom de todo (como aliás indica o título do issue) quando se tenta abrir uma área. Como mencionei, parece-me desnecessário e distrativo que aconteça zoom no momento de selecionar e abrir uma área do mapa. Cito-me na parte que para mim foi o core do comentário de abertura:

> Já que o duplo clique é usado para abrir links de áreas delimitadas do mapa (distritos, municípios, etc.), seria melhor que esse evento não resultasse também num zoom do mapa, já que se torna um pouco confuso o que está a acontecer.

E quando dizes que o clique para zoom é importante, podes especificar em que sentido? Tendo em conta o que eu disse acima: 

> Havendo já a possibilidade de fazer zoom com o botão ➕ e mouse scroll, acho que não ficaria nenhuma funcionalidade prejudicada se isto fosse implementado.

**Comment by waldyrious** [comment]
De qualquer forma, it's no big deal se preferires deixar o zoom — já não há aqui propriamente um bug, agora que o desvio do centro do mapa já não acontece. Apenas acho que é uma UX estranha e ligeiramente confusa.

**Comment by jfoclpf** [comment]
Porque o clique (simples) não faz apenas zoom, mas permite também que o mapa se centre nessa região e tal é uma _feature_ fixe do ponto de vista de UI/UX. Experimenta clicar (clique simples) nos vários distritos.

**Comment by jfoclpf** [comment]
BTW, criei o JSON=belo :)

ora vê

https://geoapi.pt/gps/38.748406,-9.102984?json=belo

João Pimentel Ferreira <https://www.joaopimentel.com>

**Comment by waldyrious** [comment]
I see. Não discordo que o efeito de centrar na área clicada seja uma boa feature, mas não me parece que seja o que está a acontecer aqui. Quando faço duplo-clique, o que acontece é um zoom in "estático" (avança sempre um nível, em vez de os níveis necessários para a área clicada ocupar o espaço do mapa), e é esse zoom que acho desnecessário e confuso, porque acontece imediatamente antes da página recarregar.

Não é possível desativar esse double-click standard zoom sem afetar o single-click smart zoom?

Quanto ao `json=belo`, nice feature, mas não percebi a relação com esta thread :sweat_smile:
