### ISSUE TITLE
Evitar cores iguais para polígonos contínuos

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/geoapi.pt#79]
![image](https://user-images.githubusercontent.com/3984909/233731945-27b0c9e2-fa41-4ab8-8093-2ab55d6c7932.png)

**Comment by waldyrious** [comment]
Engraçado que estão a ser usadas mais do que 4 cores, quando [só com 4 devia ser possível](https://en.wikipedia.org/wiki/Four_color_theorem) evitar cores contínuas :)

**Comment by jfoclpf** [comment]
O problema é implementar isso ;) 

já perguntei no stackoverflow, porque não é algo intuitivo 

https://stackoverflow.com/questions/76079820/how-to-apply-the-four-colour-theorem-on-geojson-feature-collection-with-leaflet#

**Comment by jfoclpf** [comment]
já me responderam 

https://gis.stackexchange.com/questions/458224/how-to-apply-the-four-colour-theorem-on-geojson-feature-collection-with-leaflet

**Comment by jfoclpf** [comment]
já está a funcionar aqui
https://stackoverflow.com/a/76082197/1243247

**Comment by waldyrious** [comment]
Boa! E assim também já fica o registo para outras pessoas que tenham o mesmo problema :) muito fixe teres usado live code snippets. 

Interessante que o resultado usa 6 cores (das 12 opções que lhe passas), em vez de 4 que seria o mínimo. Presumo que seja uma questão de performance?

**Comment by jfoclpf** [comment]
Boas @waldyrious 

Já implementei, que te parece?

https://geoapi.pt/municipio/porto/freguesias

https://geoapi.pt/distrito/porto/freguesias

https://geoapi.pt/distrito/porto/municipios 

https://geoapi.pt/

**Comment by waldyrious** [comment]
Funciona bem, não há de facto cores iguais adjacentes. Mas pergunto-me se seria possível configurar o algoritmo para que seja menos agressivo na minimização de cores. Ele parece tentar as cores por uma ordem fixa (presumo eu que seguindo a ordem da lista em qua são passadas), mesmo quando podia usar outras. Por exemplo:

![image](https://user-images.githubusercontent.com/478237/233847116-86f674d0-eae3-4564-9e1c-65faedd566df.png)

Aqui parece que ele coloriu a área 1, depois a área adjacente 2, depois as áreas adjacentes 3/4/5 (aqui introduzindo o amarelo), e depois 6/7/8/9 (aqui introduzindo o vermelho), e depois regressou às cores iniciais, e só voltou a usar o vermelho quando ficou sem opções entre as cores mais acima. O efeito é que excepto nos casos com muitas áreas, o mapa acaba por ser dominado por três cores primárias (verde, amarelo e roxo).

Por um lado, penso que conhecendo o teorema das 4 cores, parece-me que devia ser possível distribuir as cores de forma mais uniforme, por exemplo escolhendo uma cor aleatória da lista (que ainda não esteja usada numa área adjacente da que se vai colorir) em vez da primeira que estiver imediatamente disponível a contar do início. Mas não sei quão configurável é o algoritmo de distribuição de cores do topojson...

**Comment by waldyrious** [comment]
Na verdade, depois de experimentar um pouco, parece-me que uma alternativa bastante mais fácil de implementar seria apenas reordenar as cores da lista, para pelo menos as primeiras serem mais diversas no espaço de tonalidade. Vou mandar um PR com uma proposta.
