### ISSUE TITLE
Freguesias

### ISSUE THREAD

**Issue by DevLeiloport** [jfoclpf/geoapi.pt#82]
Boas, 

Será possível localizar a freguesia com base no código postal ? 

Cumps

**Comment by jfoclpf** [comment]
sim, não será 100% fiável, mas sim, basta detectar a freguesia do centro
vê por exemplo este CP
https://geoapi.pt/cp/2495-300
há de aparecer as coordenadas do centro, clica lá em cima, e tens a freguesia

basta fazeres dois pedidos consecutivos 

parece-te bem?

**Comment by jfoclpf** [comment]
@DevLeiloport are you there?

**Comment by DevLeiloport** [comment]
Boa tarde;

Desculpa a demora na resposta, sim, serve perfeitamente.

Obrigado desde já pela ferramenta.
JP
