### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/geoapi.pt#84]
Boas @joao e @waldyrious 

já é possível colocar esta API a correr na vossa máquina de uma forma muito fácil com o docker; podem apenas por favor testar na vossa máquina por favor?

Basta correrem do vosso lado

```
docker run -p 8080:8080 jfoclpf/geoapi.pt:latest
```

muito obrigado

**Comment by joao** [comment]
Olá, @jfoclpf.

Estamos em sintonia, ainda no outro dia experimentei criar um ficheiro Dockerfile para deployment no serviço fly.io. Após processar os dados criou uma imagem Docker de ~3.3GB (se me recordo correctamente), contudo depois não fiz _deployment_ pois surgiram-me algumas questões que aproveito para colocar:

- o projecto em produção assenta em vários domínios: geoapi.pt, json.geoapi.pt, docs.geoapi.pt Existe mais algum?
- se alguém efectuar _deployment_ do projecto, os domínios estão _hardcoded_ ou responderá a qualquer domínio a apontar para o serviço _node_? Contudo deve ser necessário pelo menos alterar manualmente no código os subdomínios, não?

Tendo isto em conta, pensei que poderia haver na raiz do projecto um ficheiro `settings.json`, em que podiam estar definido variáveis globais importantes para personalizar, nomeadamente: domínios, nível de pedidos por minuto permitidos por um IP, etc.
Haverá mais coisas a configurar se necessário?

Quanto tiver mais vagar vou tentar testar o teu ficheiro Dockerfile em produção.
Já aogra, parabéns pela funcionalidade de converter lat/lng para uma localização contextual, muito boa!

**Comment by jfoclpf** [comment]
Boas @joao fixe que estejas a tentar fazer um deployment para o fly.io

- não, o projeto assenta apenas nesses 3 domínios que mencionas
- em princípio os domínios não estão hardcoded no código, vem tudo do ficheiro [`configs.json`](https://github.com/jfoclpf/geoapi.pt/blob/main/configs.json) que está na raiz do projeto

Depois dá notícias se conseguiste pôr a funcionar, qualquer dúvida diz

**Comment by joao** [comment]
Oh, não reparei nesse ficheiro em que já tinhas abstraido os domínios.

Obrigado, vou experimentar!

**Comment by jfoclpf** [comment]
Boas @joao 
vou fechar o issue, se entretanto precisares de ajuda com o docker diz, mas deve estar tudo operacional

basta 

```sh
docker run -p 8080:8080 jfoclpf/geoapi.pt:latest
```

para colocares a API a funcionar

**Comment by rguedes** [comment]
Sugestão: Em vez das configurações ficarem apenas dependentes do config.json, podiam ser lidas a partir do ENV, facilitava o deploy por docker/docker compose.

Neste momento, temos que fazer bind do config.json fora do container, com o ficheiro interno. 

Com o ENV, o override pode ser feito a nível do compose.yaml, por exemplo:
     
 environment:
            jsonApiOrigin: "http://url-json-api.pt"

**Comment by jfoclpf** [comment]
> Sugestão: Em vez das configurações ficarem apenas dependentes do config.json, podiam ser lidas a partir do ENV, facilitava o deploy por docker/docker compose.
> 
> Neste momento, temos que fazer bind do config.json fora do container, com o ficheiro interno.
> 
> Com o ENV, o override pode ser feito a nível do compose.yaml, por exemplo:
> 
> environment: jsonApiOrigin: "http://url-json-api.pt"

```sh
docker run -e geoapipt_mainTitle='A minha GEO API' \
-e geoapipt_description='Esta é a minha API personalizada' \
-e geoapipt_defaultOrigin='https://geoapi.mydomain.pt' \
-p 8080:8080 \
jfoclpf/geoapi.pt:latest
```
