### ISSUE TITLE
Impossível acessar dados de freguesias com nomes que contenham "/" (ex Longueira/Almograve)

### ISSUE THREAD

**Issue by hensou** [jfoclpf/geoapi.pt#86]
Primeiramente obrigado por esta API e o vosso trabalho.

Quando listamos as freguesias de Odemira usando o link https://geoapi.pt/municipios/odemira/freguesias?json=1 temos a seguinte resposta:

```json
{
  "nome": "Odemira",
  "freguesias": [
    "Boavista dos Pinheiros",
    "Colos",
    "Longueira/Almograve",
    "Luzianes-Gare",
    "Relíquias",
    "Sabóia",
    "Santa Clara-a-Velha",
    "São Luís",
    "São Martinho das Amoreiras",
    "São Salvador e Santa Maria",
    "São Teotónio",
    "Vale de Santiago",
    "Vila Nova de Milfontes"
  ],
  "geojsons": { }
}
```

O problema agora é quando tentamos acessar os dados de **Longueira/Almogarve** , o cliente, penso que corretamente, faz a transformação do caractere especial e gera a seguinte url https://geoapi.pt/municipio/odemira/freguesia/longueira%2Falmograve?json=1, porém essa url nos gera o erro:

```json
{
  "erro": "Caminho não encontrado; ler instruções em https://docs.geoapi.pt"
}
```

Essa consulta também falha na página do frontend https://geoapi.pt/municipio/odemira/freguesia/longueira%2Falmograve

Outras rotas com problemas:
- [União das freguesias de Vila Cova do Covelo/Mareco](https://geoapi.pt/municipios/Penalva%20do%20Castelo/freguesias/Uni%C3%A3o%20das%20freguesias%20de%20Vila%20Cova%20do%20Covelo/Mareco?json=1)
- [Valbom/Bogalhal](https://geoapi.pt/municipios/pinhel/freguesias/Valbom/Bogalhal?json=1)
- [União das freguesias de Santa Cruz/Trindade e Sanjurge](https://geoapi.pt/municipios/chaves/freguesias/Uni%C3%A3o%20das%20freguesias%20de%20Santa%20Cruz/Trindade%20e%20Sanjurge?json=1)

**Comment by jfoclpf** [comment]
Boas, obrigado pelo reporte, estou aqui há uma hora de volta do problema.

Mas já descobri, [é um problema do NGINX](https://stackoverflow.com/questions/8264239/nginx-unescapes-2f-to-a-forward-slash-how-can-i-stop-it) que aparentemente "escapa" quando não devia.

Ainda não vi como solucionar, mas uma alternativa poderá ser alterar o nome de todas as freguesias substituindo `/` por `e`

**Comment by jfoclpf** [comment]
Já está a funcionar, diz-me o que achas, exemplo:

https://geoapi.pt/municipio/odemira/freguesia/longueira%2Falmograve
https://geoapi.pt/municipios/pinhel/freguesias/Valbom%2fBogalhal

não te esqueças que precisas de codificar a `/` para `%2f`. A função JS `encodeURIComponent()` faz isso.

**Comment by hensou** [comment]
@jfoclpf agora já funciona perfeitamente.
Muito obrigado!

**Comment by jfoclpf** [comment]
Sempre às ordens. Qualquer problema adicional reporta sff.

Saudações
