### ISSUE TITLE
Transferir dados de codigos postais e respetivas coordenadas geográficas para uma tabela.

### ISSUE THREAD

**Issue by joaocps** [jfoclpf/geoapi.pt#87]
Olá @jfoclpf 

Estava a explorar a pasta "res" porque precisava de guardar em base de dados os dados relativos a todos os códigos-postais e respetivas ruas/casas mas não estou a ver bem como o posso fazer. Estou a fazer alguma confusão relativamente ao que é a pasta admins-addresses e postal-codes e como extrair esses dados sem ter de andar a percorrer toda a estrutura de pastas 😮

O que eu precisava era de popular uma tabela com uma estrutura de [DD,CC,FF,CP4,CP3,RUA,CASA,LATITUDE,LONGITUDE], mas neste momento não estou a perceber de que modo posso fazer isso em tempo útil.

Podes-me dar alguma ideia/ajuda?

**Comment by jfoclpf** [comment]
Olá @joaocps 

Já experimentaste ir directamente à nossa fonte de dados? Nós usamos o OpenAdresses e vamos buscar o ZIP aqui:
 https://box.wolan.net/geoapi/pt_addresses.csv.zip

Podias esclarecer que campos são esses DD, CC, FF? 

Alternativamente podes correr esta API na tua máquina, e depois simplesmente fazeres vários pedidos na tua máquina usando o caminho /gps ou /cp

**Comment by jfoclpf** [comment]
Calculo que DD, CC e FF sejam respectivamente distrito, Concelho e Freguesia, mas queres todas as freguesias do país? E para estas todos os códigos postais? E para estes quais coordenadas?

**Comment by joaocps** [comment]
Olá!

Vou verificar a fonte nesse caso! Esses DD,CC,FF é os codigos respetivos do ine, acho que é uma nomenclatura só usada por mim e nem me apercebi quando o escrevi :)

**Comment by jfoclpf** [comment]
Mas como queres associar cada freguesia a coordenadas? Não é claro. 

As coordenadas são do código postal ou do centro da freguesia?

**Comment by joaocps** [comment]
Estaria a pensar em associar as coordenadas de cada código postal ...

**Comment by joaocps** [comment]
> Olá @joaocps
> 
> Já experimentaste ir directamente à nossa fonte de dados? Nós usamos o OpenAdresses e vamos buscar o ZIP aqui: https://box.wolan.net/geoapi/pt_addresses.csv.zip
> 
> Podias esclarecer que campos são esses DD, CC, FF?
> 
> Alternativamente podes correr esta API na tua máquina, e depois simplesmente fazeres vários pedidos na tua máquina usando o caminho /gps ou /cp

Este ficheiro parece ser exatamente o que necessito ... Para obter o codigo ine faço request local na api pela coordenada e consigo saber assim.

**Comment by jfoclpf** [comment]
Fixe, vou fechar o tópico, qualquer coisa adicional pergunta
