### ISSUE TITLE
Pesquisa por morada

### ISSUE THREAD

**Issue by jsilva-pt** [jfoclpf/geoapi.pt#88]
Olá João, 

Antes demais, excelente trabalho! Muito bom projeto.

A minhas questôes são se está nos planos:
- Poder pesquisar por uma morada e obter sugestões (para usar num autocomplete)
- Poder pesquisar por uma marada incluindo ou não múmero da porta e caso exista retornar também informações tais como código postal, freguesia, município, distrito, latitude, longitude ...

Obrigado

**Comment by jfoclpf** [comment]
Olá @jsilva-pt 
isso que pedes é geocodificação, e não o fizemos porque o Open Street Maps (também gratuito e open source) já faz isso.
https://nominatim.org/release-docs/latest/api/Search/

por exemplo, pesquisar info sobre Rua Fernando Maurício, 30, Lisboa

https://nominatim.openstreetmap.org/search?format=json&street=30%20rua%20fernando%20maur%C3%ADcio&city=lisboa&countrycodes=pt&addressdetails=1

**Comment by jfoclpf** [comment]
vou fechar, qualquer dúvida adicional diz
