### ISSUE TITLE
Código postal mostra mapa em branco

### ISSUE THREAD

**Issue by waldyrious** [jfoclpf/geoapi.pt#89]
Acontece aqui: https://geoapi.pt/cp/4700-500

**Comment by waldyrious** [comment]
Para contexto, esse código aparece como o CP associado a este ponto: https://geoapi.pt/gps/41.49545103848285,-8.505513931228037

**Comment by jfoclpf** [comment]
@waldyrious obrigado pelo reporte
ele vai sacar este ficheiro. 
https://github.com/jfoclpf/geoapi.pt/blob/main/res/postal-codes/data/4700/500.json

Parece que falta info relevante e é preciso agir em conformidade

**Comment by jfoclpf** [comment]
resolvido
https://geoapi.pt/cp/4700-500

obrigado @waldyrious
