### ISSUE TITLE
Novo caminho /distritos/base

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/geoapi.pt#92]
Neste momento o caminho `/distritos` retorna muitos detalhes sobre os distritos e a resposta é muito grande

Criar novo caminho `/distritos/base` cuja resposta é apenas uma lista (JSON Array) com os nomes dos distritos.

**Comment by jfoclpf** [comment]
tens razão, mas mudar agora isso não seria backwards compatible e criar um /v2 está fora de questão pois iria dar imenso trabalho 

e sim, /base dá-nos uma versão simplificada

**Comment by waldyrious** [comment]
Ok, mas nesse caso acho que a representação HTML de `/distritos` devia ser consistente com o que é apresentado atualmente em JSON, e /distritos/base (em HTML) deveria ser semelhante a https://geoapi.pt/municipios/.

**Comment by jfoclpf** [comment]
concordo

**Comment by jfoclpf** [comment]
feito, confirmar 
- https://geoapi.pt/distritos
- https://geoapi.pt/distritos?json=belo
- https://geoapi.pt/distritos/base
- https://geoapi.pt/distritos/base?json=belo

**Comment by waldyrious** [comment]
Isto se calhar devia ser um issue separado, mas o output HTML em https://geoapi.pt/municipios/ não devia ser igual ao de https://geoapi.pt/distritos/base, isto é, sem links? é que no JSON também aparecem links. Se entendi bem, para a API ser RESTFUL temos de garantir uma interface uniforme, e não personalizar o output de acordo com o formato de saída.
