### ISSUE TITLE
Lista de todos os códigos postais

### ISSUE THREAD

**Issue by Caracks** [jfoclpf/geoapi.pt#93]
Olá,

Após ler a documentação, parece-me que não é possível através da API extrair todos os códigos postais, como é possível com a lista de todos os distritos

Obrigado

**Comment by jfoclpf** [comment]
bem visto, vou implementar

**Comment by jfoclpf** [comment]
@waldyrious sugeres `/cp` ou `/cp/base`?

**Comment by waldyrious** [comment]
Depende... Se pusermos isso em `/cp/base`, o que é que ficaria em `/cp`?

**Comment by jfoclpf** [comment]
bem visto @waldyrious , vou colocar em `/cps`, o padrão do s no final é comum nos outros caminhos, `/municipios` vs `/município/aveiro` etc.

**Comment by waldyrious** [comment]
E porque não `/codigos-postais`? Fica mais claro e acho que não ganhamos muito em ter a versão curta.

**Comment by waldyrious** [comment]
Se dá para mantermos os redirects sem grande dificuldade, acho que vale a pena usar o URL mais explícito :)

**Comment by jfoclpf** [comment]
já li que em APIs o recomendado não é fazer redirect, mas manter os dois e colocar o antigo na documentação como deprecated

**Comment by jfoclpf** [comment]
@Caracks e @waldyrious 

no vosso entender o caminho `/codigos-postais` devia devolver que resultados?

1) Uma simples lista completa de CP7=CP4-CP3: `[1000-000, ..., 9999-999]`

2) Um lista de CP4, cada elemento tendo a lista respetiva dos CP3: `{1000: [000, ..., 999], ..., 9999: [000, ..., 999]}`

3) Ter caminhos separados: `/codigos-postais/cp7` devolve 1) e `/codigos-postais/cp4` devolveria `[1000, ..., 999]`

Se 2) for o resultado de `/codigos-postais` pode perfeitamente conviver com 3)

**Comment by jfoclpf** [comment]
Ou seja, parece-vos bem assim?

 - `/codigos-postais` => `{1000: [000, ..., 999], ..., 9999: [000, ..., 999]}`
 - `/codigos-postais/cp7` => `[1000-000, ..., 9999-999]`
 - `/codigos-postais/cp4` => `[1000, ..., 999]`

**Comment by Caracks** [comment]
Boas @jfoclpf 
Diria que a primeira opção (`/codigos-postais => {1000: [000, ..., 999], ..., 9999: [000, ..., 999]}`) é a que me faz mais sentido

**Comment by waldyrious** [comment]
Acho que podia ser boa ideia termos um design escalável, no sentido de no futuro poder-se acrescentar mais informação ao output (p.ex. distrito/município/freguesia, designação postal, etc.). Ou seja, talvez algo como `/codigos-postais` retornar 

```
{
  1000: { 000: {}, ..., 999: {} }
  ...,
  9999: { 000: {}, ..., 999: {} }
}
```

Cada CP7 podia ser inicialmente associado a um objeto vazio, `{}`, e assim podia-se depois acrescentar campos quer aos CP4 quer aos CP7 nessa estrutura, sem quebrar a compatibilidade.

Para conveniência, a lista simples de CP7, como um flat array (`[1000-000, ..., 9999-999]`), podia ser colocada em `codigos-postais/base` (embora eu não goste muito do nome `/base`, já existe o precedente e por isso seria consistente). Não sei se ganhamos muito em ter uma listagem simples de CP4, até porque pode ser facilmente filtrada a partir da lista de CP7s, mas isso deixo para quem usa esses dados opinar :slightly_smiling_face:.

**Comment by waldyrious** [comment]
Por um lado, isto pode ser otimização prematura, e redundante com o output que já se consegue obter individualmente via `cp/1234-567` e `cp/1234` (futuramente `codigo-postal/1234-567` e `codigo-postal/1234-567`, presumo?). Mas por outro, isso permitiria obter dados de vários CPs num único pedido; e mesmo que não acrescentemos esses detalhes aqui, sempre podemos querer acrescentar links ao estilo `JSON-HAL`, por isso penso que se pode justificar a estrutura um pouco mais complexa de nested objects.

**Comment by jfoclpf** [comment]
para já, já mudei `/cp` para `/codigo_postal` com 9f97b0e

 - https://json.geoapi.pt/codigo_postal/2495-300
 - https://geoapi.pt/codigo_postal/2495-300

teve de ser em snake case, daí o underscore `_`

**Comment by jfoclpf** [comment]
Para concluir, vou então implementar

### `/codigos_postais` 

```
{
  1000: { 000: {}, ..., 999: {} }
  ...,
  9999: { 000: {}, ..., 999: {} }
}
```

### `/codigos_postais/base` 

```
["1000-000", ..., "9999-999"]
```

Está bem para vocês @waldyrious e @Caracks ?

**Comment by jfoclpf** [comment]
feito:
 - https://geoapi.pt/codigos_postais
 - https://geoapi.pt/codigos_postais/base
 - https://json.geoapi.pt/codigos_postais
 - https://json.geoapi.pt/codigos_postais/base
